from enum import Enum


class TransactionStatus(str, Enum):
    FAILED = "FAILED"
    ABANDONED = "ABANDONED"
    RECOVERED = "RECOVERED"
    UNRECOVERABLE = "UNRECOVERABLE"


class CaseStatus(str, Enum):
    DETECTED = "DETECTED"
    DIAGNOSING = "DIAGNOSING"
    ACTION_PENDING = "ACTION_PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"


class ActionType(str, Enum):
    RAZORPAY_PAYMENT_LINK = "RAZORPAY_PAYMENT_LINK"
    SMART_RETRY = "SMART_RETRY"
    WHATSAPP_NUDGE = "WHATSAPP_NUDGE"
    EMAIL_NOTIFICATION = "EMAIL_NOTIFICATION"


class ActionStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ActorType(str, Enum):
    AI_AGENT = "AI_AGENT"
    SYSTEM_RULE = "SYSTEM_RULE"
    MERCHANT_ADMIN = "MERCHANT_ADMIN"
    WEBHOOK = "WEBHOOK"
